apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec: 
  selector: 
    matchLabels:
      app: api-conversao
  template:
    metadata: 
      labels: 
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: giovannijakubiak/api-conversao:v1
          ports: 
            - containerPort: 5000

---


apiVersion: v1
kind: Service
metadata: 
  name: api-conversao
spec: 
  selector: 
    app: api-conversao
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
    type: nodePort